### ISSUE TITLE
Internal Server Error (500)

### ISSUE THREAD

**Issue by Gizmo0815** [microsoft/azure-boards-automate-state-transitions#17]
I followed the setup instructions but keep getting an "Internal Server Error (500)" when testing the service hook:

```
Failed
Sent at: Wednesday, 30. October 2019 15:35:09
Message
Bug #5 (Some great new idea!) updated by Jamal Hartnett.
Error Message
Internal Server Error (500)
```

Any ideas what I'm doing wrong?

**Comment by danhellem** [comment]
Have you tried to take a body of the message and post that to the service while in debug mode?

You can use the swagger endpoint to do it manually.

**Comment by cvialatte** [comment]
Hi,

Same here. Your repository needs a httpClient and I think it is not well regsitered in the service provider.

regards

**Comment by cvialatte** [comment]
Ok, I figured out the issue. The way you register the cliuent is wrong. Please just register the client factory :  services.AddHttpClient();

Then in RulesRepo, inject the factory and use it to create the client, someting like
`public class RulesRepo : IRulesRepo, IDisposable
    {
        private IOptions<AppSettings> _appSettings;
        private IHelper _helper;
		private readonly IHttpClientFactory _clientFactory;

		public RulesRepo(IOptions<AppSettings> appSettings, IHelper helper, IHttpClientFactory clientFactory)
        {
            _appSettings = appSettings;
            _helper = helper;
			_clientFactory = clientFactory;
        }

        public async Task<RulesModel> ListRules(string wit)
        {
            string src = _appSettings.Value.SourceForRules;
			var client = _clientFactory.CreateClient();

			var request = new HttpRequestMessage(HttpMethod.Get, src + "/rules." + wit.ToLower() + ".json");

			var response = await client.SendAsync(request);
			if (response.IsSuccessStatusCode)
			{
				var json = await response.Content.ReadAsStringAsync();
				RulesModel rules = JsonConvert.DeserializeObject<RulesModel>(json);
				return rules;

			}
			else
			{
				return new RulesModel();
			}

        }`

You will have to handle bad requests...

**Comment by vaclavholusa-LTD** [comment]
Just remove the line `services.AddTransient<IRulesRepo, RulesRepo>();` from `Startup.cs`

**Comment by Gizmo0815** [comment]
I removed the line but I'm still getting the Internal server error as response:
`Status Code: 500
Reason Phrase: Internal Server Error
HTTP Version: 1.1
Headers:
{
  Date: Thu, 13 Feb 2020 10:48:06 GMT
  Set-Cookie: ARRAffinity=f36c8130531c157fc790e7052450319f91d9a1fed78535477b558504530e1fd5;Path=/;HttpOnly;Domain=autostatetransitions20200213102712.azurewebsites.net
  Server: Microsoft-IIS/10.0
  X-Powered-By: ASP.NET
  Content-Length: 0
}
`

**Comment by vaclavholusa-LTD** [comment]
Please enable stdout logging in your web.config to see the exact error. This is very general, can't help

**Comment by TAK-WTW** [comment]
Same issue for me, don't think this code has been tested properly

**Comment by danhellem** [comment]
@TAK-WTW @Gizmo0815 what happens when you step through the code in debug mode?

**Comment by Gizmo0815** [comment]
@danhellem The implementation of this solution was too cumbersome for me. I created an Azure Logic App that traggers on updates of tasks, gets the parent work item and sets its state to active. 

Here's the logic app, if someone wants to do the same:
![logicapp](https://user-images.githubusercontent.com/16947043/77151646-abe87b80-6a96-11ea-84d2-63dc24729627.png)

**Comment by bbarman4u** [comment]
> @danhellem The implementation of this solution was too cumbersome for me. I created an Azure Logic App that triggers on updates of tasks, gets the parent work item and sets its state to active.
> 
> Here's the logic app, if someone wants to do the same:

Excellent suggestion @Gizmo0815 ! I will also definitely look into this instead of trying to deploy a full web app into the Azure Infrastructure unless some complicated processing logic was needed.

Wondering how much do you incur in monthly charge on average if when you are using the logic app?

**Comment by Gizmo0815** [comment]
> Wondering how much do you incur in monthly charge on average if when you are using the logic app?

That depends on the usage of your DevOps. For our region an execution costs 0,000025 US$. We have a team of 30 developers using Azure DevOps. On an average day we have ~100 updates that trigger the logic app. Assuming 20 working days per month the execution costs are somewhere around 5 cts/mo. 

To get an impression for your organization I would set up a webhook that fires on updates of tasks and puts a message into an Azure queue for one day. At the end of the day you can just count the messages in the queue and do the math for your organization.

**Comment by bbarman4u** [comment]
> > Wondering how much do you incur in monthly charge on average if when you are using the logic app?
> 
> That depends on the usage of your DevOps. For our region an execution costs 0,000025 US$. We have a team of 30 developers using Azure DevOps. On an average day we have ~100 updates that trigger the logic app. Assuming 20 working days per month the execution costs are somewhere around 5 cts/mo.
> 
> To get an impression for your organization I would set up a webhook that fires on updates of tasks and puts a message into an Azure queue for one day. At the end of the day you can just count the messages in the queue and do the math for your organization.

Thank you @Gizmo0815 for the nice suggestions. I am less familiar with the Azure Logic Apps and hence please pardon my  questions. Is there any other monthly integration fees that needs to be paid with the logic apps integration with the Azure DevOps ?

**Comment by Gizmo0815** [comment]
@bbarman4u I checked the costs on the azure website and found out that my last post was partially incorrect. Each action used within the logic app costs 0,000025 US$ (not one execution of the whole app). For details on pricing and connectors check out https://azure.microsoft.com/en-us/pricing/details/logic-apps/.

**Comment by bbarman4u** [comment]
> @bbarman4u I checked the costs on the azure website and found out that my last post was partially incorrect. Each action used within the logic app costs 0,000025 US$ (not one execution of the whole app). For details on pricing and connectors check out https://azure.microsoft.com/en-us/pricing/details/logic-apps/.

@Gizmo0815 Thanks again for this suggestion.
I tried out by creating a logic app and integrating into the Azure DevOps. The flow of the logic app is like this and works fine for my current needs. Also I checked that the billing cost is quite minimal on a daily basis. For the complex needs I guess I will have to try out this extension.

![image](https://user-images.githubusercontent.com/20643454/84541089-46361500-acbc-11ea-927a-7d76d730526e.png)
