### ISSUE TITLE
Stuck at step 3 deploying

### ISSUE THREAD

**Issue by dstmm** [microsoft/azure-boards-automate-state-transitions#18]
Hello,

I really like the idea and I want to implement it but I'm stuck at step 3:
_Deploy the project so that it is available from the Azure DevOps instance._
Where can I find more information about how to do this? (How & Where should I deploy etc)
Thanks in advance!

Kind regards.

**Comment by danhellem** [comment]
you need to deploy so that API is accessible from Azure DevOps. Meaning it can't be hidden behind a firewall

**Comment by mstephano** [comment]
Can the project be upgraded to .NET Core 3.1 LTS please? Azure Web App can only install 2.1 or 3.1 LTS, not 2.2?

Can you also be more specific on how and where to deploy? I assume in Azure Web App right?

**Comment by danhellem** [comment]
Yeah azure web app....i have not looked at the repo in a few months. Should be able to upgrade though. i will take a look and get it done in a few days

**Comment by mstephano** [comment]
Great, thank you @danhellem . I am already using the failed pull request from someone who upgraded to 3.0. I did upgrade to 3.1 and managed to publish to Azure.

However, I still can't get my Azure DevOps to properly communicate to the web api. I always get 500 Internal Server Error. Can you guide me quickly on how to setup logs when the update web api failed?

**Comment by danhellem** [comment]
The best way to debug it is to just just run the service in debug mode in Visual Studio. Then cut and past the webhook payload in the body text and step through the code

**Comment by danhellem** [comment]
@mstephano  yes, the organization name is needed in order for the api to communicate with your instance of azure devops

**Comment by mstephano** [comment]
Ok, I have worked all day on this project and was able to deploy to an Azure Web App and everything is working fine now with my DevOps board. All my work item states are changing automatically based on my rules.json files. You can check my fork at https://github.com/mstephano/azure-boards-automate-state-transitions

@dstmm @danhellem In order to debug locally, I had to do like you said. I used the payload sent from DevOps and using Postman to send the POST method with body to my local server. I was then able to debug the source code in Visual Studio 2019.

Changes I made:
- update to .NET Core 3.1
- moved rules.*.json files under wwwroot/rules so they are deployed with the website
  - because of this move, relative path to the root of the website can now be used for "SourceForRules" in the appsettings.json file
  - "rules" is now the default value for "SourceForRules" in appsettings.json file
- adjust the source code to work with .NET Core 3.1
  - had to removed every `using (WorkItemTrackingHttpClient client = connection.GetClient<WorkItemTrackingHttpClient>())` and replaced with only `var client = connection.GetClient<WorkItemTrackingHttpClient>();`
  - removed unnecessary/buggy line `services.AddTransient<IRulesRepo, RulesRepo>();`
- add files "rules.feature.json" and "rules.product backlog item.json" as example
- updated readme to tell users to put their organization in the appsettings.json file

If anyone needs help with their installation, let me know!

**Comment by bbarman4u** [comment]
> Ok, I have worked all day on this project and was able to deploy to an Azure Web App and everything is working fine now with my DevOps board. All my work item states are changing automatically based on my rules.json files. You can check my fork at https://github.com/mstephano/azure-boards-automate-state-transitions
> 
> @dstmm @danhellem In order to debug locally, I had to do like you said. I used the payload sent from DevOps and using Postman to send a POST method with body to my local server. I was then able to debug the source code in Visual Studio 2019.
> 
> Changes I made:
> 
> * update to .NET Core 3.1
> * moved rules.*.json files under wwwroot/rules so they are deployed with the website
>   
>   * because of this move, relative path to the root of the website can now be used for "SourceForRules" in the appsettings.json file
>   * "rules" is now the default value for "SourceForRules" in appsettings.json file
> * adjust the source code to work with .NET Core 3.1
>   
>   * had to removed every `using (WorkItemTrackingHttpClient client = connection.GetClient<WorkItemTrackingHttpClient>())` and replaced with only `var client = connection.GetClient<WorkItemTrackingHttpClient>();`
>   * removed unnecessary/buggy line `services.AddTransient<IRulesRepo, RulesRepo>();`
> * add files "rules.feature.json" and "rules.product backlog item.json" as example
> * updated readme to tell users to put their organization in the appsettings.json file
> 
> If anyone needs help with their installation, let me know!

@mstephano thanks for the detailed write up on the issues faced by you as well as providing path to your fork. Are you able to raise a PR to merge to the main repo with the fixes that you have already ? Also I was wondering how much time would it take for a non dot net guy to configure and deploy this and debug it if necessary without using Visual Studio (I have visual studio code).

**Comment by zaherrinspire** [comment]
> Ok, I have worked all day on this project and was able to deploy to an Azure Web App and everything is working fine now with my DevOps board. All my work item states are changing automatically based on my rules.json files. You can check my fork at https://github.com/mstephano/azure-boards-automate-state-transitions
> 
> @dstmm @danhellem In order to debug locally, I had to do like you said. I used the payload sent from DevOps and using Postman to send a POST method with body to my local server. I was then able to debug the source code in Visual Studio 2019.
> 
> Changes I made:
> 
> * update to .NET Core 3.1
> * moved rules.*.json files under wwwroot/rules so they are deployed with the website
>   
>   * because of this move, relative path to the root of the website can now be used for "SourceForRules" in the appsettings.json file
>   * "rules" is now the default value for "SourceForRules" in appsettings.json file
> * adjust the source code to work with .NET Core 3.1
>   
>   * had to removed every `using (WorkItemTrackingHttpClient client = connection.GetClient<WorkItemTrackingHttpClient>())` and replaced with only `var client = connection.GetClient<WorkItemTrackingHttpClient>();`
>   * removed unnecessary/buggy line `services.AddTransient<IRulesRepo, RulesRepo>();`
> * add files "rules.feature.json" and "rules.product backlog item.json" as example
> * updated readme to tell users to put their organization in the appsettings.json file
> 
> If anyone needs help with their installation, let me know!

Thanks @mstephano, your solution works great. One thing I noticed though is that Bugs state doesn't change to Active if the child Task state becomes Active. However, if you close the Task, the Bug state changes.

**Comment by bbarman4u** [comment]
> > Ok, I have worked all day on this project and was able to deploy to an Azure Web App and everything is working fine now with my DevOps board. All my work item states are changing automatically based on my rules.json files. You can check my fork at https://github.com/mstephano/azure-boards-automate-state-transitions
> > @dstmm @danhellem In order to debug locally, I had to do like you said. I used the payload sent from DevOps and using Postman to send a POST method with body to my local server. I was then able to debug the source code in Visual Studio 2019.
> > Changes I made:
> > 
> > * update to .NET Core 3.1
> > * moved rules.*.json files under wwwroot/rules so they are deployed with the website
> >   
> >   * because of this move, relative path to the root of the website can now be used for "SourceForRules" in the appsettings.json file
> >   * "rules" is now the default value for "SourceForRules" in appsettings.json file
> > * adjust the source code to work with .NET Core 3.1
> >   
> >   * had to removed every `using (WorkItemTrackingHttpClient client = connection.GetClient<WorkItemTrackingHttpClient>())` and replaced with only `var client = connection.GetClient<WorkItemTrackingHttpClient>();`
> >   * removed unnecessary/buggy line `services.AddTransient<IRulesRepo, RulesRepo>();`
> > * add files "rules.feature.json" and "rules.product backlog item.json" as example
> > * updated readme to tell users to put their organization in the appsettings.json file
> > 
> > If anyone needs help with their installation, let me know!
> 
> Thanks @mstephano, your solution works great. One thing I noticed though is that Bugs state doesn't change to Active if the child Task state becomes Active. However, if you close the Task, the Bug state changes.

@zaherrinspire Please check out an enhanced version of @mstephano solution here in my repo that takes care of slightly advanced scenarios around handling multiple scenarios. Also I have made edits to discourage storing the PAT in the source code. Note - organization name is not required in the appsettings.json file.
Here is the link - [Repo URL ](https://github.com/bbarman4u/azure-boards-automate-state-transitions)

**Comment by bbarman4u** [comment]
hello

> > > Ok, I have worked all day on this project and was able to deploy to an Azure Web App and everything is working fine now with my DevOps board. All my work item states are changing automatically based on my rules.json files. You can check my fork at https://github.com/mstephano/azure-boards-automate-state-transitions
> > > @dstmm @danhellem In order to debug locally, I had to do like you said. I used the payload sent from DevOps and using Postman to send a POST method with body to my local server. I was then able to debug the source code in Visual Studio 2019.
> > > Changes I made:
> > > 
> > > * update to .NET Core 3.1
> > > * moved rules.*.json files under wwwroot/rules so they are deployed with the website
> > >   
> > >   * because of this move, relative path to the root of the website can now be used for "SourceForRules" in the appsettings.json file
> > >   * "rules" is now the default value for "SourceForRules" in appsettings.json file
> > > * adjust the source code to work with .NET Core 3.1
> > >   
> > >   * had to removed every `using (WorkItemTrackingHttpClient client = connection.GetClient<WorkItemTrackingHttpClient>())` and replaced with only `var client = connection.GetClient<WorkItemTrackingHttpClient>();`
> > >   * removed unnecessary/buggy line `services.AddTransient<IRulesRepo, RulesRepo>();`
> > > * add files "rules.feature.json" and "rules.product backlog item.json" as example
> > > * updated readme to tell users to put their organization in the appsettings.json file
> > > 
> > > If anyone needs help with their installation, let me know!
> > 
> > 
> > Thanks @mstephano, your solution works great. One thing I noticed though is that Bugs state doesn't change to Active if the child Task state becomes Active. However, if you close the Task, the Bug state changes.
> 
> @zaherrinspire Please check out an enhanced version of @mstephano solution here in my repo that takes care of slightly advanced scenarios around handling multiple scenarios. Also I have made edits to discourage storing the PAT in the source code. Note - organization name is not required in the appsettings.json file.
> Here is the link - [Repo URL ](https://github.com/bbarman4u/azure-boards-automate-state-transitions)

@zaherrinspire Additionally [here](https://github.com/bbarman4u/azure-boards-automate-state-transition-serverless) is an updated version of this code which is rewritten to run using Azure Functions.

**Comment by zaherrinspire** [comment]
Thanks @bbarman4u, I will give a try to the serverless option. Thanks!

Regarding the previous issue reported, this turned out to be caused by work item rules for required fields which are enforced once the status changes to Active.
