### ISSUE TITLE
Can we write a rule using same code for other conditions

### ISSUE THREAD

**Issue by prashanthbv12** [microsoft/azure-boards-automate-state-transitions#20]
Hello,

For example if state new is selected, in sub states it should only populate values as “New bug” or “reopened” (Sub state is a custom picklist  field)
And if state is committed,  substate should show “Ready for grooming” or ready for implementation.
If State done is selected then sub state should only show values in the pick like "Fixed" or "Nor a Bug"..

Please help

**Comment by danhellem** [comment]
As of right now the code does not support those sub states. But the solution is open source. So feel free to download and do as you need. I don't think there is a team to support any new features to this code right now.
